### ISSUE TITLE
Can't run without --net=host

### ISSUE THREAD

**Issue by diutsu** [linuxserver/docker-plex#40]
Pretty much what it says in the title, plus:
````
diutsu@heimdall: sudo docker create \  
  --name="plex" \
  -e version=latest \
  -e PUID=0 -e PGID=0 \
  -p 32400:32400 \
  -p 32400:32400/udp \
  -p 32469:32469 \
  -p 32469:32469/udp \
  -p 5353:5353/udp \
  -p 1900:1900/udp \
  -v /data/tmp/plx:/config \
  -v /data/tmp/tv:/data/tvshows \
  -v /data/tmp/movies:/data/movies \
  linuxserver/plex

5278c85286403410ae6e52367b61e76365eb3e5141a7804c440787bbd64ced5d
diutsu@heimdall: sudo docker start plex
Error response from daemon: Container command '/sbin/my_init' not found or does not exist.
Error: failed to start containers: plex
````

also, if I run with an equivalent docker compose it outputs even more stuff:
````
Starting plex

ERROR: for plex  b"Container command '/sbin/my_init' not found or does not exist."
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 58, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 109, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 734, in up
    remove_orphans=remove_orphans)
  File "/usr/lib/python3.5/site-packages/compose/project.py", line 402, in up
    'Encountered errors while bringing up the project.'
compose.project.ProjectError: Encountered errors while bringing up the project.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
````

Am I doing this wrong or missing a port?

**Comment by sparklyballs** [comment]
i would suspect that using PGID AND PUID = 0 for root is the main issue here.

**Comment by sparklyballs** [comment]
closed, running with ports defined is covered in readme but is not actively encouraged or supported.
